USE players_db;

DROP TABLE IF EXISTS players;


CREATE TABLE players(
  id INT(11) NOT NULL AUTO_INCREMENT, 
  fname CHAR(50) NOT NULL,
  sname CHAR(50) NOT NULL,
  games INT(5) NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
)ENGINE=InnoDB, DEFAULT CHARACTER SET utf8;

